### ISSUE TITLE
The app no longer works when following the installation steps correctly in the past it worked but some updates later it seems completely broken.

### ISSUE THREAD

**Issue by CRCODE22** [Eddycrack864/UVR5-UI#12]
Installing collected packages: multipart
Successfully installed multipart-1.1.0

(base) K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app>run-UVR5-UI.bat
Traceback (most recent call last):
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\app.py", line 8, in <module>
    import gradio as gr
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 7, in <module>
    from gradio.components.base import Component, FormComponent
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\components\annotated_image.py", line 14, in <module>
    from gradio import processing_utils, utils
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\processing_utils.py", line 33, in <module>
    from gradio.route_utils import API_PREFIX
  File "K:\Users\CRCODE22\pinokio\api\uvr5-ui.git\app\env\lib\site-packages\gradio\route_utils.py", line 34, in <module>
    import multipart
ModuleNotFoundError: No module named 'multipart'

Press any key to continue . . .

**Comment by CRCODE22** [comment]
Pinokio is the problem manually cloning this github and executing "UVR5-UI-installer.bat" and then "run-UVR5-UI.bat" it works :)

**Comment by Eddycrack864** [comment]
Interesting, I thought it didn't work through Pinokio. I'll check this out so it can be used through Pinokio too again.
