### ISSUE TITLE
getting this error but it still works?

### ISSUE THREAD

**Issue by SUP3RMASS1VE** [Eddycrack864/UVR5-UI#22]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\gradio\route_utils.py", line 790, in __call__   
    await self.app(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\routing.py", line 715, in __call__    
    await self.middleware_stack(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\routing.py", line 288, in handle      
    await self.app(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\responses.py", line 348, in __call__  
    await self._handle_simple(send, send_header_only)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "F:\pinokio\api\UVR5-WebUI.git\app\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length

**Comment by Eddycrack864** [comment]
CSS is not loading correctly right? I mean... I've seen that error before when I tried to update it on Hugging Face, and the app would work but it would look void of any layout because the CSS wouldn't load properly. I see you are using Pinokio, to be honest I have not tried using it through Pinokio so if you get any errors I'm not sure how to solve them, if it is usable it's fine I think, if not I would recommend you install it without Pinokio.

**Comment by Eddycrack864** [comment]
I was checking your work and you can try this to make it work properly... try downgrading gradio to version 4.44.1, there might be problems with gradio_i18n (due to Gradio version) or yt-dlp (websockets library) but if you don't need to translate you can remove that library and all that translation stuff, and for yt-dlp you can use an older version if websockets version is incompatible.

**Comment by Eddycrack864** [comment]
I made the official port of [UVR5 UI to pinokio](https://github.com/Eddycrack864/UVR5-UI-pinokio) and this bug was fixed.
