### ISSUE TITLE
The system cannot find the specified file

### ISSUE THREAD

**Issue by TestP3** [Eddycrack864/UVR5-UI#25]
My version of gradio: is 4.44.1
To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 790, in __call__
    await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 790, in __call__
    await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "C:\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
2024-12-22 03:09:14,376 - ERROR - separator - FFmpeg is not installed. Please install FFmpeg to use this package.
Traceback (most recent call last):
  File "C:\UVR5-UI\app.py", line 222, in mdxc_separator
    separator = Separator(
  File "C:\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 182, in __init__
    self.setup_accelerated_inferencing_device()
  File "C:\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 189, in setup_accelerated_inferencing_device
    self.check_ffmpeg_installed()
  File "C:\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 216, in check_ffmpeg_installed
    ffmpeg_version_output = subprocess.check_output(["ffmpeg", "-version"], text=True)
  File "C:\Users\e_abe\Miniconda3\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\e_abe\Miniconda3\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\e_abe\Miniconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\e_abe\Miniconda3\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the specified file
-------------------
after its removal from 2 websockets folders :
 File "C:\UVR5-UI\app.py", line 5, in <module>
    import gradio as gr
  File "C:\UVR5-UI\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\UVR5-UI\env\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\UVR5-UI\env\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 7, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\UVR5-UI\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\UVR5-UI\env\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    import gradio_client.utils as client_utils
  File "C:\UVR5-UI\env\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\UVR5-UI\env\lib\site-packages\gradio_client\client.py", line 38, in <module>
    from gradio_client import utils
  File "C:\UVR5-UI\env\lib\site-packages\gradio_client\utils.py", line 28, in <module>
    from websockets.legacy.protocol import WebSocketCommonProtocol
ModuleNotFoundError: No module named 'websockets'

**Comment by Eddycrack864** [comment]
The problem is due to the gradio version, gradio versions <5.0 had a problem with 3 libraries: pydantic, fastapi and starlette. You have to install specific versions of those libraries as shown [here](https://github.com/Eddycrack864/UVR5-UI/commit/7b64e675796880c06ce1ec3c562ed9e54466d470). About websockets I'm not sure but there might be problems with yt_dlp due to the version.

I really recommend you to use gradio >5 as described in the requirements.txt, I'm not sure how you installed UVR5 UI but you can use the [installer](https://github.com/Eddycrack864/UVR5-UI?tab=readme-ov-file#getting-started). Also don't forget to install [FFmpeg](https://github.com/Eddycrack864/UVR5-UI?tab=readme-ov-file#prerequisites).

**Comment by TestP3** [comment]
I will do what you indicate, however the installation was as follows, in my C:// disk, I created a folder called:
UVR5-UI, then inside the folder Clone your repository as you indicate, before installing I updated my python version, from torch +CUDA 2.14, I installed gradio, yt_dlp. try to update, now I will try again.

**Comment by Eddycrack864** [comment]
Oh, I see. No need to install everything manually, my installer installs everything automatically, including its own version of python. You probably have some other dependencies installed globally and this causes conflicts

**Comment by TestP3** [comment]
I just upgraded to the versions you ask for in requirements.txt, and I had also forgotten to set the ffmpeg environment variables, and now it seems to work perfectly. My question is how do I make it use my GPU to render, it is only using my cpu and it is a bit slow.
I don't know if it is: that I had to create a virtual environment in the env folder, and install torch, because when I wanted to import in the code I thought it would be solved, how can I change to CUDA?

**Comment by Eddycrack864** [comment]
That's because the audio-separator[gpu] library installs torch by default and not torch with CUDA support.

To resolve this follow these steps:
1. Uninstall torch and torchvision via `pip uninstall torch torchvision`
2. Reinstall that libraries specifying the installation index for torch via `pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121`

**Comment by TestP3** [comment]
Now with the update, it is perfect.
Is there any way, to have the MelBand Roformer / Bas Curtiz edition models?

**Comment by Eddycrack864** [comment]
Nope, that model is paid. Only available on MVSEP iirc

**Comment by TestP3** [comment]
OH! :(
