### ISSUE TITLE
404 errors when selecting some models. 

### ISSUE THREAD

**Issue by Dryesthalo98066** [Eddycrack864/UVR5-UI#27]
Hello, I was messing around with different models when I found out that some cant seem to be found when the program tries to download them. For example when I try to use MelBand Roformer Kim | Inst V2 by Unwa I get this error in CMD (Its long I put the whole log of my CMD). I have only tested some of the MelBand Roformer models and have not tried any others so im not sure if this is only an issue with the new models or not. Thank you for any help!

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 789, in __call__
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 500, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 570, in download_model_files
    self.download_file_if_not_exists(yaml_url, download_path)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 345, in download_file_if_not_exists
    raise RuntimeError(f"Failed to download file from {url}, response code: {response.status_code}")
RuntimeError: Failed to download file from https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/mdx_model_data/mdx_c_configs/config_melbandroformer_inst_v2.yaml, response code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\app.py", line 247, in roformer_separator
    separator.load_model(model_filename=roformer_model)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 672, in load_model
    model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 574, in download_model_files
    self.download_file_if_not_exists(yaml_url, download_path)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 345, in download_file_if_not_exists
    raise RuntimeError(f"Failed to download file from {url}, response code: {response.status_code}")
RuntimeError: Failed to download file from https://github.com/nomadkaraoke/python-audio-separator/releases/download/model-configs/config_melbandroformer_inst_v2.yaml, response code: 404

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\blocks.py", line 2047, in process_api
    result = await self.call_function(
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio\utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "C:\AIStuffCDrive\UVR5-UI\app.py", line 255, in roformer_separator
    raise RuntimeError(f"Roformer separation failed: {e}") from e
RuntimeError: Roformer separation failed: Failed to download file from https://github.com/nomadkaraoke/python-audio-separator/releases/download/model-configs/config_melbandroformer_inst_v2.yaml, response code: 404

**Comment by Eddycrack864** [comment]
That's not good, I'll check it tomorrow. It seems that file has been removed from the repos.

U can import manually, here is the repo on HF: https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/tree/main

**Comment by Dryesthalo98066** [comment]
Cool, thanks!

**Comment by Eddycrack864** [comment]
Fixed! Now the models/config files are downloaded correctly

**Comment by Dryesthalo98066** [comment]
Awesome thanks!
